#Variables
title: cs-ib
slogan: IB Computer Science
description: Student-written Resources for the IB Computer Science Course. Following the syllabus for 2014+ and organized by topic.
author: Miguel Guse
email: gusemiguel@gmail.com
github_username: mwmg

#Settings
baseurl: ""
url: "https://www.cs-ib.net"
#url: "http://127.0.0.1:4000"
#http://www.cs-ib.net.s3-website-ap-southeast-1.amazonaws.com
# http://www.cs-ib.net
#host: localhost
#port: 4000

#include pages
include: ["_pages"]
collections:
    sections:
        output: true
    topic:
        output: true
destination: ./docs
exclude:
    - package.json
    - node_modules
    - gulpfile.js
    - bower_components

plugins:
    - jekyll-sitemap
    - jekyll-minifier
